version: '2'
services:
  postgres:
      image: postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=123456
          - PGDATA=/var/lib/pgdata
          - DATABASE_URL=postgres://username:pgpassword@db:5432
      volumes:
          - ./pgdata:/var/lib/pgdata
      ports:
          - "5432:5432"
      expose:
       - "5432"